### ISSUE TITLE
RuntimeError: The underlying hash algorithm has not yet been initialized.

### ISSUE THREAD

**Issue by tomoyoirl** [pcorliss/ruby_route_53#10]
I've got a script which looks something like this; it's about as simple as I could come up with.

```
def shakedown
    conn = Route53::Connection.new(@key, @secret)
    puts conn.get_zones.inspect
end
```

It results in a backtrace like the following.```
    RuntimeError: The underlying hash algorithm has not yet been initialized.
     /Users/me/.rvm/gems/ruby-1.9.2-p180@snet/gems/ruby-hmac-0.4.0/lib/hmac.rb:36:in`check_status'
     /Users/me/.rvm/gems/ruby-1.9.2-p180@snet/gems/ruby-hmac-0.4.0/lib/hmac.rb:68:in `update'
     /Users/me/.rvm/gems/ruby-1.9.2-p180@snet/gems/route53-0.2.1/lib/route53.rb:41:in`request'
     /Users/me/.rvm/gems/ruby-1.9.2-p180@snet/gems/route53-0.2.1/lib/route53.rb:63:in `get_zones'
     /Users/me/git/ops/dns.rb:19:in`shakedown'

```
```

**Comment by recurser** [comment]
Thanks @pcorliss - I had the same issue, and it turned out that `key` and `secret` were blank.
