### ISSUE TITLE
DNSRecord class does not support health check - pull request done for it.

### ISSUE THREAD

**Issue by patrickviet** [pcorliss/ruby_route_53#39]
it's on https://github.com/pcorliss/ruby_route_53/pull/38
this simple 4 line diff solves the problem.

Usage example:

Route53::DNSRecord.new("www.#{name}","A","60",["1.2.3.4"],zone,nil,10,'someidentifier',false,"339743f3-33de-4670-ad0d-17b75985d339").create

**Comment by pcorliss** [comment]
Fixed via #38
