### ISSUE TITLE
change all records in hosted zone

### ISSUE THREAD

**Issue by gabayliran** [pcorliss/ruby_route_53#41]
is it possible to change all TTL records to hosted zone without to choose one by one ?
"Please select the record to perform the action on."

**Comment by pcorliss** [comment]
Unfortunately the command line tool doesn't have the ability to make multiple changes in a single transaction. You can use the library to do this however, see the second on change sets.

With some shell magic you can achieve something similar though. The following would change the ttl of all of your CNAME records to 300 seconds.
```bash
route53 -l --zone example.com. | grep CNAME | cut -d' ' -f1 | xargs -n1 route53 -g --zone example.com. --ttl 300 --no-wait --name
```

**Comment by gabayliran** [comment]
Thank you, real magic !
is it possible to change all CNAME records on all hosted zone with one command ?

**Comment by pcorliss** [comment]
Not from the command line. But the library, which the command line uses behind the scenes, can make a change to multiple records at once.

**Comment by gabayliran** [comment]
thank you very much for your help, this project much helpful !
